# ansible-playbook abstraction.yml -e process_name="SIX-STREAM"
---
- name: Run task to find field in dict
  hosts: node1
  tasks:
    - include_tasks: steps/execute_step.yml
      vars:
#        execute: get_process_list_by_group
#        with_group: "FIX-LTQSW-7"
#        with_entry: configScript
        execute: parse_list
        with_error: "error"
    - debug:
        var: execution_report
