- name: Play - install Nginx
  hosts: debian_group
  tasks:
  - name: Checking Repositories (update)
    apt:
      update_cache: yes
      cache_valid_time: 3600
  - name: Installing Nginx
    apt:
      name: ['nginx']
      state: latest
  - name: Starting Web Server
    service:
      name: nginx
      state: started
      enabled: true
  - name: smoke test
    uri:
      url: http://localhost
      return_content: yes
