---
- name: "[Setup] Init report collection"
  hosts: debian_group
  vars:
    server_status_list: {}
  tasks:
  - name: "check space"
    include_tasks: check_space.yml
    register: check_space
    ignore_errors: true

  - name: "check something else"
    block:
      - include_tasks: check_space.yml
    rescue:
      register: check_something_else

  - name: "print"
    debug:
      msg: "{{ check_space }}"

  - name: "print"
    debug:
      msg: "{{ check_something_else }}"
